### ISSUE TITLE
support for extend

### ISSUE THREAD

**Issue by bhavinkamani** [sindresorhus/broccoli-jade#1]
Does this plugin supports auto recompilation of jade files that uses `extend` directive? I have following simple set of templates and Brocfile.js

`app/_layout.jade`

```
doctype html
html
  head
    meta(http-equiv='Content-Type', content='text/html; charset=utf-8')
    meta(name="viewport", content="width=device-width, initial-scale=1, maximum-scale=1")

  body
    h1 Broccoli-jade
    block content
```

`app/index.jade`

```
extends _layout
block content
  p This allows you to use index.static.jade instead of index.html for brunch! ...
```

`Brocfile.js`

```
var pickFiles = require('broccoli-static-compiler')
var processJade = require('broccoli-jade')

appFiles = pickFiles('app', {
  srcDir: '/',
  destDir: ''
})
module.exports = processJade(appFiles, {filename: 'app/_layout'})
```

It recompiles `_layout.jade` into `_layout.html`. However, the dependent template (`index.jade`) is left as it is unless broccoli is restarted.

**Comment by jayliu50** [comment]
+1

Looking around on github, it appears that jade depends on the cli tool that wraps jade to handle dependencies. Jade exposes the dependent files.

https://github.com/jadejs/brjade/issues/1
https://github.com/jadejs/jade/issues/1086

**Comment by sindresorhus** [comment]
This project is deprecated.
