### ISSUE TITLE
Include paths are relative to Brocfile, not to jade file

### ISSUE THREAD

**Issue by fredrikekelund** [sindresorhus/broccoli-jade#5]
I have a project layout like this:

```
Brocfile.js
app/
    index.jade
    views/
        my-file-to-include.jade
build/
```

When running broccoli from the root of my project, an broccoli-jade throws an error that the include path `views/my-file-to-include.jade` in `index.jade` can't be resolved. If I instead write it as `app/views/my-file-to-include.jade`, it's resolved. I would consider this behavior a bug, since I expect import paths to be resolved relative to the jade file, not to the Brocfile.

**Comment by sindresorhus** [comment]
This project is deprecated.
