### ISSUE TITLE
Load included files from Broccoli input tree

### ISSUE THREAD

**Issue by kylecordes** [sindresorhus/broccoli-jade#7]
Currently, this plug-in does not appear to notice included files changing to realize a rebuild is necessary. This suggests that it is not currently loading those included files from the broccoli input tree, but rather is looking past broccoli, directly to the file system. I'm not sure if this diagnosis is correct, but it does seem to explain that the problematic (and I'm pretty confident, erroneous) behavior.

I think this is also related to another open item, but I'm not 100% sure. Fix wanted.

**Comment by GammaNu** [comment]
I have the same issue :
Here is my Brocfile.js :
```javascript
var jade = require('broccoli-jade');
var stylus = require('broccoli-stylus');

var tree = 'src/';
tree = stylus(tree, {});
tree = jade(tree, {});

module.exports = tree;
```
and my src/index.jade :
```jade
doctype html
html(lang="fr")
	head
		title my title
		style
			include style.css
	body
		h1 my title
```
and my src/style.styl :
```stylus
*
	color red
```
the stylus step is done before the jade step so it should work, but it does'nt.
Any fix ?
Regards,
Millicent Billette

**Comment by GammaNu** [comment]
problem solved, by using an other module : 
```js
var stylus = require('broccoli-stylus');
var renderTemplates = require("broccoli-render-template");

var tree = 'src/';

tree = stylus(tree, {});
tree = renderTemplates(tree,{pretty:true});

module.exports = tree;
```
with these dependency in place of `broccoli-jade` :     `broccoli-render-template` and `jade`

**Comment by kylecordes** [comment]
I have also switched to broccoli-render-template, it fixes this problem and supports Jade and more.

**Comment by kylecordes** [comment]
Yet another alternative:

https://github.com/akvadrako/broccoli-jade-render

(It is almost as if search engines do not exist. Why bother to find an existing tool, and improve it? Better to start yet another alternative to do the same time...)

**Comment by sindresorhus** [comment]
This project is deprecated.
